import type { Product, ProductCategory } from "@/types/product";

export const productCategories = ["Biryani", "Pizza", "Burger", "Sandwich"] as const;

export const categoryIcons: Record<ProductCategory, { src: string; imageClassName: string }> = {
  Biryani: {
    src: "/foods/biryani-1.jpg",
    imageClassName: "object-cover object-center",
  },
  Pizza: {
    src: "/foods/pizza-1.jpg",
    imageClassName: "object-cover object-center",
  },
  Burger: {
    src: "/foods/burger-2.jpg",
    imageClassName: "object-cover object-center",
  },
  Sandwich: {
    src: "/foods/sandwich-2.jpg",
    imageClassName: "object-cover object-center",
  },
};

export const products: Product[] = [
  {
    id: "hyderabadi-biryani",
    name: "Hyderabadi Biryani",
    cardTitle: "Hyderabadi Biryani",
    detailHeading: "Biriyani Bliss",
    category: "Biryani",
    image: "/foods/biryani-1.jpg",
    detailImage: "/foods/biryani-1.jpg",
    rating: 4.8,
    reviewCount: 1050,
    distance: "2.5 km",
    time: "20 min delivery",
    price: 7.5,
    calories: "450 Cal",
    diameter: "15.05 Cm",
    description:
      "Hyderabadi biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender meat, and fragrant basmati rice. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Small",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-74px] top-3 h-[356px] w-[334px]",
    detailRoundedClassName: "rounded-full",
  },
  {
    id: "bombay-biryani",
    name: "Bombay Biryani",
    cardTitle: "Bombay Biryani",
    detailHeading: "Biriyani Bliss",
    category: "Biryani",
    image: "/foods/biryani-2.jpg",
    detailImage: "/foods/biryani-2.jpg",
    rating: 4.5,
    reviewCount: 1320,
    distance: "3.5 km",
    time: "25 min delivery",
    price: 8.5,
    calories: "380 Cal",
    diameter: "15.05 Cm",
    description:
      "Bombay biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,mater and fragrant basmati rice. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Medium",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-54px] top-3 h-[344px] w-[310px]",
    detailRoundedClassName: "rounded-[34px]",
  },
  {
    id: "onion-capsicum-pizza",
    name: "Onion Capsicum Pizza",
    cardTitle: "Onion Capsicum Pizza",
    detailHeading: "Pizza Bliss",
    category: "Pizza",
    image: "/foods/pizza-1.jpg",
    detailImage: "/foods/pizza-1.jpg",
    rating: 4.9,
    reviewCount: 1550,
    distance: "2.5 km",
    time: "20 min delivery",
    price: 10.5,
    calories: "480 Cal",
    diameter: "18.05 Cm",
    description:
      "Onion capsicum pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender onion and capsicum and fragrant pizza base. originating from the vibrant city of the Hyderabad in India, this is iconic dish......",
    defaultSize: "Large",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-82px] top-7 h-[348px] w-[352px]",
    detailRoundedClassName: "rounded-full",
  },
  {
    id: "panner-pizza",
    name: "Panner Pizza",
    cardTitle: "Panner Pizza",
    detailHeading: "Pizza Bliss",
    category: "Pizza",
    image: "/foods/pizza-2.jpg",
    detailImage: "/foods/pizza-2.jpg",
    rating: 4.2,
    reviewCount: 1130,
    distance: "3.5 km",
    time: "25 min delivery",
    price: 9.5,
    calories: "460 Cal",
    diameter: "12.05 Cm",
    description:
      "Panner and mater pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,mater and fragrant pizza base. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Small",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-38px] top-10 h-[348px] w-[294px]",
    detailRoundedClassName: "rounded-full",
  },
  {
    id: "veg-burger",
    name: "Veg Burger",
    cardTitle: "Veg Burger",
    detailHeading: "Burger Bliss",
    category: "Burger",
    image: "/foods/burger-1.jpg",
    detailImage: "/foods/burger-1.jpg",
    rating: 4.2,
    reviewCount: 1130,
    distance: "2.5 km",
    time: "20 min delivery",
    price: 12.5,
    calories: "560 Cal",
    diameter: "6.05 Cm",
    description:
      "Veg burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender aalu tiki and tamato,other and fragrant burger base. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Medium",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-82px] top-[48px] h-[300px] w-[350px]",
    detailRoundedClassName: "rounded-[36px]",
  },
  {
    id: "paneer-burger",
    name: "Paneer Burger",
    cardTitle: "Paneer Burger",
    detailHeading: "Burger Bliss",
    category: "Burger",
    image: "/foods/burger-2.jpg",
    detailImage: "/foods/burger-2.jpg",
    rating: 4.6,
    reviewCount: 1230,
    distance: "3.5 km",
    time: "25 min delivery",
    price: 8.5,
    calories: "460 Cal",
    diameter: "4.00 Cm",
    description:
      "Panner burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu tiki and tamato,other and fragrant burger base. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Medium",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-120px] top-[56px] h-[290px] w-[388px]",
    detailRoundedClassName: "rounded-[34px]",
  },
  {
    id: "veg-sandwich",
    name: "Veg Sandwich",
    cardTitle: "Veg Sandwich",
    detailHeading: "Sandwich Bliss",
    category: "Sandwich",
    image: "/foods/sandwich-2.jpg",
    detailImage: "/foods/sandwich-2.jpg",
    rating: 4.6,
    reviewCount: 1230,
    distance: "2.5 km",
    time: "20 min delivery",
    price: 7.5,
    calories: "460 Cal",
    diameter: "4.00 Cm",
    description:
      "Veg sandwich is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and fragrant burger base. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Medium",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-2px] top-[46px] h-[350px] w-[256px]",
    detailRoundedClassName: "rounded-full",
  },
  {
    id: "potato-sandwich",
    name: "Potato Sandwich",
    cardTitle: "Potato Sandwich",
    detailHeading: "Sandwich Bliss",
    category: "Sandwich",
    image: "/foods/sandwich-1.jpg",
    detailImage: "/foods/sandwich-1.jpg",
    rating: 4.6,
    reviewCount: 1343,
    distance: "3.5 km",
    time: "25 min delivery",
    price: 6.5,
    calories: "460 Cal",
    diameter: "4.00 Cm",
    description:
      "Potato sandwich is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and fragrant burger base. originating from the vibrant city of the Hyderabad in india, this is iconic dish......",
    defaultSize: "Medium",
    sizes: ["Small", "Medium", "Large"],
    cardImageClassName: "object-cover object-center",
    detailImageClassName: "object-cover object-center",
    detailContainerClassName: "absolute right-[-8px] top-[44px] h-[354px] w-[264px]",
    detailRoundedClassName: "rounded-full",
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id);
}
